email_task:
  description: >
    Write an email about {topic}. 
    Make sure to write it in a well structured manner, the date is {current_date}, My name is {my_name}, recipient's name is {recipient_name}.
    Use these if applicable: Colleague Name: {colleague_name}, colleague's phone number: {colleague_number}.
  expected_output: >
    An email with proper formatting for {topic}, which will be sent on {application}. 
    At the end it will have my signature:{my_signature}
    Return only a valid JSON object that strictly follows this structure: {syntax}
    Do not include any extra text, markdown formatting (like ```json), or explanation.
    Just return a clean, parsable JSON object as output that can be directly sent via Microsoft Graph API.
    Your response **must not include** markdown fences, comments, or extra explanation.
    Output should be a **pure JSON object**, ready to be parsed by `json.loads()`.
  agent: email_writer


