email_task:
  description: >
    Write an email about {topic}. 
    Based on the document provided in the knowledge source (e.g. attachment.txt or .docx),
    write a personalized email summarizing the key points of the document,
    explaining what it is about, and why it is relevant to the recipient.
    Make sure to write it in a well structured manner, the date is {current_date}, My name is {my_name}, recipient's name is {recipient_name}.
    Use these if applicable: Colleague Name: {colleague_name}, colleague's phone number: {colleague_number}.

    You are writing a weekly progress update email about {topic} from {my_name} to {recipient_name}. 
    Use the contents of the attached document (provided in the knowledge source) as your primary context. 
    This document contains detailed information about {my_name}'s weekly work activities, accomplishments, tasks, and any notable updates.
    
    Your task is to:
    - Carefully read and summarize the content of the document.
    - Extract key work activities and organize them clearly in the email.
    - Explain what was done, what progress was made, and any important context that the recipient should be aware of.
    - Maintain a formal, respectful tone suitable for emailing a supervisor.
    - Clearly mention the current date: {current_date}.
    - End the email with a polite closing and signature: {my_signature}.
    - Mention any colleagues involved if relevant, such as {colleague_name} and their contact {colleague_number}.

    Do **not** invent or assume details. Only use what is present in the document.

  expected_output: >
    An email with proper formatting for {topic}, which will be sent on {application}. 
    At the end it will have my signature:{my_signature}
    Return only a valid JSON object that strictly follows this structure: {syntax}
    Do not include any extra text, markdown formatting (like ```json), or explanation.
    Just return a clean, parsable JSON object as output that can be directly sent via Microsoft Graph API.
    Your response **must not include** markdown fences, comments, or extra explanation.
    Output should be a **pure JSON object**, ready to be parsed by `json.loads()`.
    Ensure the content reflects the actual content of the attached document — do not use placeholders like [Update 1] or [Document Name].

  agent: email_writer


