email_task:
  description: >
    You are writing a weekly update email about {topic} from {my_name} to {recipient_name}. 
    
    Your task is to:
    - Clearly mention the current date: {current_date}.
    - End the email with a polite closing and signature: {my_signature}.
    - Mention any colleagues involved if relevant, such as {colleague_name} and their contact {colleague_number}.

    Do **not** invent or assume details. Only use what is present in the document.

  expected_output: >
    An email with proper formatting for {topic}, which will be sent on {application}. 
    At the end it will have my signature:{my_signature}
    Return only a valid JSON object that strictly follows this structure: {syntax}
    Do not include any extra text, markdown formatting (like ```json), or explanation.
    Just return a clean, parsable JSON object as output that can be directly sent via Microsoft Graph API.
    Your response **must not include** markdown fences, comments, or extra explanation.
    Output should be a **pure JSON object**, ready to be parsed by `json.loads()`.
    Ensure the content reflects the actual content of the attached document — do not use placeholders like [Update 1] or [Document Name].

  agent: email_writer


